id: ICFDBDC12
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T11:45:00+00:00'
last_modified: '2022-06-10T09:15:37.365055+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23151
  title: གསུང་འབུམ། བློ་བཟང་ཚུལ་ཁྲིམས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    9FFB:
      image_group_id: I1KG8795
      title: Volume 1 of gsung 'bum/_blo bzang tshul khrims/
      total_pages: 714
      order: 1
      base_file: 9FFB.txt
    AC96:
      image_group_id: I1KG8796
      title: Volume 2 of gsung 'bum/_blo bzang tshul khrims/
      total_pages: 801
      order: 2
      base_file: AC96.txt
    E91E:
      image_group_id: I1KG8797
      title: Volume 3 of gsung 'bum/_blo bzang tshul khrims/
      total_pages: 700
      order: 3
      base_file: E91E.txt
    E688:
      image_group_id: I1KG8798
      title: Volume 4 of gsung 'bum/_blo bzang tshul khrims/
      total_pages: 656
      order: 4
      base_file: E688.txt
    '2986':
      image_group_id: I1KG8799
      title: Volume 5 of gsung 'bum/_blo bzang tshul khrims/
      total_pages: 647
      order: 5
      base_file: 2986.txt
    '6269':
      image_group_id: I1KG8800
      title: Volume 6 of gsung 'bum/_blo bzang tshul khrims/
      total_pages: 657
      order: 6
      base_file: 6269.txt
    00D8:
      image_group_id: I1KG8801
      title: Volume 7 of gsung 'bum/_blo bzang tshul khrims/
      total_pages: 612
      order: 7
      base_file: 00D8.txt
    D81A:
      image_group_id: I1KG8802
      title: Volume 8 of gsung 'bum/_blo bzang tshul khrims/
      total_pages: 700
      order: 8
      base_file: D81A.txt
    '4989':
      image_group_id: I1KG8803
      title: Volume 9 of gsung 'bum/_blo bzang tshul khrims/
      total_pages: 454
      order: 9
      base_file: 4989.txt
    017C:
      image_group_id: I1KG8804
      title: Volume 10 of gsung 'bum/_blo bzang tshul khrims/
      total_pages: 553
      order: 10
      base_file: 017C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
